### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#10]
Big Red App was used because that's what it used to be called. But, after talking with @lidavidm, it would be a good idea to at least kick off an issue about whether this should be named something different.

I originally named the old app Big Red App, because despite it focusing on dining, it handled academic halls, facilities like libraries and fitness centers, bus stops on campus, etc. So, I had decided to make it a more abstract name. Additionally, I had considered Cornell App, or something, but was worried about branding issues. It might be worth asking Cornell staff.

Now, as for this app, it brings up the question, should this app try to get into other things besides Cornell Dining halls? I'm worried about bloat, but e.g. something simple like the open hours of the Libraries could be useful. This influences the name, because if that does happen, then if a new name is decided upon, I don't think it would be good to have it be focused on just dining.

But anyway, I am 100% open to any input on this.

**Comment by lidavidm** [comment]
Hmm, if we have lots of disparate info it'll be hard to come up with a name that covers everything but isn't generic.

At least for bus stops, I think that should be a separate app, and I think someone I know is actually working on it. The bus schedules alone are pretty complex and people will probably want stuff like route planning.

If we stick solely to 'open hours' for various facilities it could be 'What's Open Big Red' or something like that.

**Comment by ghost** [comment]
Yeah, I'm with you there. I like the idea of sticking to the idea of campus facilities, and that direction of the name. I'll keep thinking about this too.

**Comment by ghost** [comment]
We are running it under Big Red App for now
