### ISSUE TITLE
RedAPI now has great calendar support, let's use it!

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#14]
Thanks to @mrkev!!
- We provide a comma-separated list of dining halls and a range, like "today-tomorrow" or "April 6, 2015-April 8, 2015".
- It supports any format that [`date.js`](http://www.datejs.com/) supports.
- We can just choose some simple output from [`Calendar`](http://developer.android.com/reference/java/util/Calendar.html) to send in for the date range.
- Sample query: [all events between April 6 and April 8 for Okenshields and North Star](http://redapi-tious.rhcloud.com/dining/event/okenshields,north_star/April%206,%202015-April%208,%202015).
- It returns ISO strings for the date in UTC time. We can use [`SimpleDateFormat`](http://developer.android.com/reference/java/text/SimpleDateFormat.html) to parse.
- He says he can make it use an epoch integer if needed (he used ISO for easier debugging) but I told him it seems fine, because SimpleDateFormat looks perfect.

**Comment by mrkev** [comment]
😁

**Comment by lidavidm** [comment]
Wow, this looks amazing. Great work @mrkev!

**Comment by ghost** [comment]
[Currently working on this, will push soonish]

**Comment by ghost** [comment]
This is by no means the last use of the calendar hours, but for now, this is done by 6a76046, so closing
