### ISSUE TITLE
Material Launcher Icon?

### ISSUE THREAD

**Issue by lidavidm** [genkimarshall/bigredapp-android#15]
This is a small thing, but I think before release this app should have a nice Material launcher icon. I'm not sure what it'd look like, though - perhaps some sort of schedule or door floating on a red background?

**Comment by ghost** [comment]
Agreed, and I like that idea. This is a pretty convenient image -> icon helper if you haven't seen it already: http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html

**Comment by lidavidm** [comment]
![image](https://cloud.githubusercontent.com/assets/327919/6999268/7581c370-dbd1-11e4-8ff7-646136c43c2c.png)

Yup, I've seen that tool. How about this, just for now? I think the "info" clipart is suitably generic.

Here's another concept (handmade):

![icon2](https://cloud.githubusercontent.com/assets/327919/6999352/1db25a66-dbd5-11e4-9a26-f6ee1be5e086.png)

**Comment by ghost** [comment]
Am I correct in guessing a little inspiration from Google Calendar?
![image](https://cloud.githubusercontent.com/assets/4513869/6999376/aaa79f66-dbd6-11e4-917a-0ce5c48aad04.png)
I like them both ^_^ Hmm.. Have you tried putting them on the phone yet to see which might seem nicer there?
I think the second one is a really neat idea.

**Comment by lidavidm** [comment]
The first one is just from the icon generator xD the second one is my idea. I haven't tried them yet (and the second one doesn't have all the necessary shadows and tints and stuff, I have no idea how to use inkscape). One sec

**Comment by ghost** [comment]
Ah haha I see. But kk sounds good no rush

**Comment by lidavidm** [comment]
On device

![screenshot_2015-04-05-21-15-21](https://cloud.githubusercontent.com/assets/327919/6999440/e2f22f7e-dbd8-11e4-8042-437686f88254.png)

**Comment by lidavidm** [comment]
Gah, the dot on the "I" isn't casting a shadow. There's also some gradients that I'm missing. Oh well. But this is the basic idea I had.

**Comment by ghost** [comment]
Yup I dig it :D Let's run with it (yeah the shadow for the dot sounds good). Hm, also could you try playing with turning the strength of the shadow down just a little? If it ends up looking worse then no prob at all, was just curious.

**Comment by lidavidm** [comment]
Oh lol I just threw in random things. I think (I hope) Google has actual values somewhere, I noticed they specified stuff like the drop shadow strength pretty exactly but didn't see anything for the long shadow.

**Comment by ghost** [comment]
Haha yeah for sure. Hm, yeah I couldn't find any after a simple search. Would think they would have had it on that icon guideline page.. Ah well.

**Comment by mrkev** [comment]
Found an [icon generator](http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=text&foreground.space.trim=0&foreground.space.pad=0.05&foreground.text.text=i&foreground.text.font=Roboto&foreColor=fff%2C0&crop=0&backgroundShape=circle&backColor=f44336%2C100&effects=shadow).

**Comment by ghost** [comment]
edit: haha that was the same one I linked above :P
I didn't know you could prefill text though, that's convenient, I just saw the image loader. I guess that's how @lidavidm was saying he made that first one?

**Comment by lidavidm** [comment]
@mrkev That's the exact one I used for the squared icon above :D

@genkimarshall The first one was made using the 'clipart' option.

![ic_launcher](https://cloud.githubusercontent.com/assets/327919/7004742/fe76d618-dc3d-11e4-8d24-de516c5a3f46.png)

**Comment by ghost** [comment]
:100: Let's run with that one :D

**Comment by mrkev** [comment]
+1 :)

**Comment by ghost** [comment]
TODO: Make David's icon the default

**Comment by ghost** [comment]
Anddd it's done! e9f594051d7fe97eadff89d3ea57bbf702c472e8 Thanks @lidavidm :D
