### ISSUE TITLE
Open hours implementation discussion

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#19]
Discussing 6a76046922ffec6615728a6e2f3bc65ca98c451b

Some notes on implementation:
- Right now it caches the list of dining halls (just their ID's) for 2 weeks using `SharedPreferences`. It's a ridiculously small size of data. I think this is reasonable for now. (But when we cache other things going forward, as discuss below, this should probably join them).
- Currently Cornell dining has an event in their Google Calendars with a summary "Closed" when the place is closed. (Though this isn't super consistent). So, when building a CalEvent list, these are simply ignored, so that when iterating through the list later, we can assume any event is an open event, and no event means closed.
- This doesn't currently live-update either the color nor the text of the hoursText for each location. I thought an implementation of that would add in a decent amount of code on top of what was already being done, so thought to leave that out in this commit. So, unfortunately, the scene has to be rebuilt (i.e. via killing the app or rotating the screen) to get updated times. Maybe a pull-to-refresh for this would be nice? Not sure.
- In the same train of thought, there definitely could be a system of caching the events, but that would also be significant code. Also, there should most likely be description of the hours for the upcoming week, or something of the sort, inside the location activity itself.
- It might be worth splitting out a `CalendarUtils` class for all that `Calendar` code..

And on the more user-facing side:
- 100% open to feedback on the implementation, aesthetics, etc. as always.

Once discussion is resolved-enough for at least this release, and any changes that come with it, we can move forward with #13

**Comment by ghost** [comment]
What it looks like at the moment:
![screenshot_2015-04-26-16-32-54](https://cloud.githubusercontent.com/assets/4513869/7339151/20668166-ec32-11e4-9ee1-79919c4753a0.png)

**Comment by mrkev** [comment]
Digging the interface. Pull to reload would be nice IMO if live updating is too complicated to implement. In any case tho I don't expect people to have this screen open for long enough stretches of time to make live updating absolutely essential.

**Comment by ghost** [comment]
Thanks :D 
Yeah, agreed. The idea of pull to refresh has been growing on me for implementing this, it makes sense in this scenario, people are used to it, etc. And like you said, live updating doesn't feel crucial by any means. And, pull to refresh will be a nice benefit for the amount of effort which is always nice :P

**Comment by ghost** [comment]
Kk added pull to refresh! Closing this one for now.
