### ISSUE TITLE
Display the location's name in the DiningListFragment, not its RedAPI id name

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#2]
I think we will wait to tackle this one until #1 is done, so that we can do one API request in onCreateView to get all the location's information. Then, that will come with it its name.
E.g. see [this return object](http://redapi-tious.rhcloud.com/dining/ivy_room) (name is at the bottom).

**Comment by lidavidm** [comment]
Ah, my list adapter doesn't use this info. I think having a custom list adapter would be necessary anyways eventually though.

**Comment by ghost** [comment]
Haha I was about to comment literally the same thing: not gonna close this until we get the new API, but for now this situation is remedied with your 42965620fe65c52a063402150d2f0cf6a20d53fb. Since we are going to need our own adapter very shortly anyway, great fix for now ^_^

**Comment by ghost** [comment]
Closed as per 37a4cffcf14c8048025549a6a8504c1daa197401
