### ISSUE TITLE
Pull to refresh is done! So how about an animation when the new items come in?

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#22]
I like [DBrady's Relay for reddit](https://play.google.com/store/apps/details?id=free.reddit.news) animation when the listings are updated. But anything good sounds good to me :P

Totally open to thoughts/opinions/questions on this.

**Comment by lidavidm** [comment]
Hmm, they're not entirely new items though...maybe just animating the time text or something? But that doesn't give as much of an indicator.

**Comment by ghost** [comment]
Yeah that's a good point actually. Hmm... I guess in reality it's not crucial that the user should know the items were refreshed, they should just be expected to be up to date?

On that note by the way, I've realized that the way I implemented the hint means basically just every new hour that you enter the app, it gives you the hint. Which seems... not so good, lol.

I think maybe a better thing would be to just have it get new data for you if the current data is >=1 hour old. So in the `onResume` of [DiningListFragment](https://github.com/genkimarshall/bigredapp-android/blob/master/app/src/main/java/is/genki/bigredapp/android/DiningListFragment.java), calling `refreshContent()` rather than displaying the hint. The user is going to refresh the data anyway, might as well do it for them is my thought process. Thoughts?

**Comment by lidavidm** [comment]
Yeah, auto-refresh, and have a manual pull-to-refresh as a placebo/in case the app got it wrong.

**Comment by ghost** [comment]
Yeah i like that :+1:

**Comment by ghost** [comment]
Resolved by e226882e1591d2812acd8b3ef8691406413f9d74
