### ISSUE TITLE
Hint about using pull to refresh

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#23]
Maybe when they first open the app, or if they use the app for some amount of time without doing it, we give them a pop-up letting them know they can pull-to-refresh the data?
I guess it's not the _most_ ideal thing, but I feel like this is a sensible and helpful thing to do.

**Comment by lidavidm** [comment]
Might be overkill, but this could use a `ShowcaseView` library, which emulates what some Google apps do (example: https://lh6.ggpht.com/C7upo-Cx63WFidih9txS-FXpprPd4YtmBim3yLd1YtYIm5m5fLytz-8EQg4qo0QAnw=h900) I can't find any that aren't being rewritten and are designed for Material, though.

**Comment by lidavidm** [comment]
Other option would be to have a first-launch thing that explains how to use the app, but that's _way_ overkill. Otherwise maybe the app could have a "Pull to Refresh" toast that pops up if the data shown is > 1 hour old, for instance.

**Comment by ghost** [comment]
Ah yeah, having a nice showcase thing would be nice. I guess waiting on them to material design it then..
But in the meantime, I like the idea of just doing that little toast, that sounds like a very non-intrusive yet helpful implementation. :+1:

**Comment by ghost** [comment]
Done :+1:
