### ISSUE TITLE
Improve Menu UI

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#30]
Good quote from Matthew:

> "To make menus easier for people to parse (some can be long!) I’m thinking of preserving the food categories somehow. One idea is: the category names aren’t all that important, but keeping foods in the same category (such as “Grill Station”) can help with readability. To subtly make groupings visible, I’m thinking of alternating the text color slightly for different groups, so that, e.g., all items in the “Grill Station” group are dark gray and grouped together, all items in the “Breakfast Station” are black and grouped together, etc. (Hopefully this makes sense). Thoughts? I suppose this is a minor point for now, but might work well."

[Still discussing this on the [OpenSourceCornell Slack](https://opensourcecornell.slack.com/signup)]

**Comment by ghost** [comment]
At the very least, this should be bullet points, because block of text is not pretty.
Maybe look into knowing whether it is like the Salad Bar.

**Comment by TrevorEdwards** [comment]
Resolved in https://github.com/TrevorEdwards/bigredapp-android/commit/0c257165ef02dfd49bf0a12718b8a6dbd9246540 .
