### ISSUE TITLE
Fix text size on Nexus 5

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#31]
I'm not sure if this is limited to Nexus 5, but the text size for example on @lidavidm's Nexus 5 was strangely too large, despite us using sp for font sizes.

**Comment by lidavidm** [comment]
Might be worth playing with an emulator. Or if you want me to take a look at a build, let me know.

**Comment by ghost** [comment]
Oh yeah great idea, I'm gonna do that soon. And sounds good, if I think I fix it, I'll ping ya :)

**Comment by ghost** [comment]
Seems to have been fixed by #32, thanks David ^_^
