### ISSUE TITLE
Add link to open location in Google Maps.

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#35]
This would simply involve first getting the coordinates of the location (I believe RedAPI supports this, will check later), and then adding in a link in the page to tap that opens it up in Google Maps.

**Comment by ghost** [comment]
See #36, location info is in that new endpoint.

**Comment by TrevorEdwards** [comment]
Resolved in https://github.com/TrevorEdwards/bigredapp-android/commit/0c257165ef02dfd49bf0a12718b8a6dbd9246540 .  The now dining feature has an option for this.
