### ISSUE TITLE
Respect user's time settings.

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#37]
Currently it forces 12-hour style e.g. "8:00 pm" when, if the user desires, it would be 24-hour style e.g. "20:00".

**Comment by TrevorEdwards** [comment]
Fixed in https://github.com/TrevorEdwards/bigredapp-android/commit/d994641a12bac5b5bfac7f0ba5dc8a7df09cdea2 :+1:

**Comment by ghost** [comment]
Haha wow, that is a beautiful fix :')
