### ISSUE TITLE
Bad Menus

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#38]
For some reason, cafes that definitely do not have all-you-can-eat menus are copying the menus of all-you-can-eat locations.

**Comment by TrevorEdwards** [comment]
It looks like this might be an API-side problem: http://redapi-tious.rhcloud.com/dining/menu/atrium_cafe/Breakfast/LOCATIONS

**Comment by ghost** [comment]
Ah awesome good notice :+1: 
Hmm, seems I can't tag Kevin, I'll link him here though.

**Comment by TrevorEdwards** [comment]
Resolved in https://github.com/TrevorEdwards/bigredapp-android/commit/0c257165ef02dfd49bf0a12718b8a6dbd9246540 .
