### ISSUE TITLE
Deceiving closing time

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#42]
Report by @TrevorEdwards.

Dining locations that close for breakfast and immediately open for lunch deceivingly say, for example that it closes at 11am, even though it is really staying open until 1pm.

This should be taken care of by `open_status`, just filing this bug for now.

**Comment by TrevorEdwards** [comment]
Resolved in https://github.com/TrevorEdwards/bigredapp-android/commit/0c257165ef02dfd49bf0a12718b8a6dbd9246540 .
