### ISSUE TITLE
Map Integration

### ISSUE THREAD

**Issue by TrevorEdwards** [genkimarshall/bigredapp-android#44]
I'd like to work on adding a new map integration feature using the GoogleMap api.  It will involve adding a slider drawer to the app so we can switch to a map fragment that will show Cornell's campus.

In the long run, we will add a few categories you can use to populate markers on the map (probably from  https://cornelldata.org/pages/mapdata.html ).  GoogleMap lets the user press a marker and get walking directions from that.  Later, we can add a search feature so you can lookup any of these places.

**Comment by ghost** [comment]
Okay awesome, sounds good to me, thank you!
So what do you think the first step should be?
Could you expand (lol) on the idea of the slider drawer?
It probably would be good to set up some sort of navigation structure, agreed.

**Comment by TrevorEdwards** [comment]
The slider drawer is basically like a hamburger menu that gmail has.  It will have all of the categories for fragments/activities our app offers (for now just dining and maps) allowing for easy navigation without taking up a lot of screen space unless necessary.  I made a basic one following the developer tutorials which you can see  [here](https://goo.gl/photos/VSy6p9wa37Jwocbx7).

**Comment by ghost** [comment]
Yeah, makes sense. I'm just wondering, going forward, what other categories for fragments/activities should we have?
I'm sure there are good ideas for some, so polling for them here.
Because one perspective is if we are already going to have tabs via #40 to just add a 3rd "Map" tab.
But, no ideas are set in my mind atm.

**Comment by TrevorEdwards** [comment]
A few other features (options for the drawer) we can add are library hours, a TCAT route finder, campus events, important phone numbers/links, and maybe class roster.  We also may want to consider putting the about page as the last option.  All of those are just suggestions though.  If we did that, then it would make sense to keep tabs in dining and make map a slider drawer option.

**Comment by louisel** [comment]
I think settings (for example setting the language for translations #43) should also be in the sliding drawer. I'll keep the tabs in the dining fragment with the sliding drawer in mind.
(An example of tabs+sliding drawer is the Play Store app, and it makes sense to have both)

**Comment by ghost** [comment]
Okay, in terms of how to divide the navigation, both comments sound reasonable to me :+1:

**Comment by ghost** [comment]
:D Nice @TrevorEdwards
