### ISSUE TITLE
Weekly Dining/Cafe Hours

### ISSUE THREAD

**Issue by Kairi700** [genkimarshall/bigredapp-android#45]
At the bottom of each dining hall or cafe, it would be a good idea to put the weekly hours for the place so that people can plan trips to places like the Dairy Bar in advance.

**Comment by ghost** [comment]
+1
(Note for history: this was discussed offline).

**Comment by TrevorEdwards** [comment]
Resolved in https://github.com/TrevorEdwards/bigredapp-android/commit/0c257165ef02dfd49bf0a12718b8a6dbd9246540 .  You can click on a location to see its full hours now.
