### ISSUE TITLE
Daily Dining Hours

### ISSUE THREAD

**Issue by Kairi700** [genkimarshall/bigredapp-android#46]
When selecting a dining hall, it would be nice to see the time period each place was open for in the headers (ex. "Breakfast (7:00-10:30)", "Lunch (11:30-2:30)", etc.)

**Comment by ghost** [comment]
+1
(Note for history: this was discussed offline).

**Comment by TrevorEdwards** [comment]
Resolved in https://github.com/TrevorEdwards/bigredapp-android/commit/0c257165ef02dfd49bf0a12718b8a6dbd9246540 .
