### ISSUE TITLE
location_status

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#48]
http://redapi-tious.rhcloud.com/dining/location_status

This will become the new source for information of the home page.
This will probably just be for #40, but it's technically a different thing, so making this separate.
Having multiple status updates will mean we can show more details about the open status for the day.
E.g. even if it's not even breakfast yet, we can note when it will open for dinner (so advanced!).

**Comment by TrevorEdwards** [comment]
This is no longer an option due to https://github.com/TrevorEdwards/bigredapp-android/commit/0c257165ef02dfd49bf0a12718b8a6dbd9246540 .
