### ISSUE TITLE
Decide some format to filter what is currently open

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#5]
Once the RedAPI has it easier to get the calendar objects (see #1), there should be some easy way to see what is currently open.
Ideas:
- Make the title green
- Have a tabbed view at the top to switch between "all" and "currently open"
- Others?
  Additionally, it would be good to get some ideas going on what sort of other filtering, if any, might be good. That's too complicated for right now, but it's good to think about going forward.

**Comment by lidavidm** [comment]
I think a nice design might be to
1. Segment the list view by location (so North Campus, Central Campus, West Campus). Maybe there could even be a "nearest to me" at the top that shows the nearest (open) cafe and dining hall.
2. Under the title, in smaller text, put "Open until xx:xx" in green, "Opening at xx:xx" in yellow if they're opening in the next n hours, or "Closed" in red otherwise.

**Comment by ghost** [comment]
1. So, are you thinking like section headers within the ListView? That would be what I had in the old BigRedApp, and I thought it worked out nicely. "Nearest to me" could be very nice, agreed, but I'd like to make the call now to put that in later after the first implementation.
2. I really like this thought. Perhaps though, it doesn't need to say if its closed in red? It would just simply not have an "Open until" nor "Opening at"? We'll just have to see which one seems nicer.

**Comment by lidavidm** [comment]
1. Yup, exactly what I was thinking. And that was just an idea, ideas are fun.
2. Since some places are only open certain days, it might be helpful to have "Closed today" to at least make it clear? I agree though, we'll have to just implement it and see.

**Comment by ghost** [comment]
1. Haha, sorry yeah, reading my response now I can imagine: "Duh Genki" but, anyway, agreed :)
2. In the effort for clarity, I think you have a good point there, so yeah, we'll just see then.

**Comment by ghost** [comment]
Since this has been implemented via green-text, I'll close this for now.

**Comment by lidavidm** [comment]
Green-text, haha...I hope we didn't implement this via 4chan ;)

**Comment by ghost** [comment]
> mfw I realize what I said
